name: kick travis

on: [push, pull_request]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: clone another repo for build activity
        uses: actions/checkout@v2  
      - name: kick travis
        run: |
          echo "CI: Github actions"
          env
          URL="https://api.github.com/repos/nvenkatapavan/github-actions3/actions/workflows/main.yaml/dispatches"
          BODY="{
          \"ref\":\"main\",
          \"inputs\": {
          \"message\":  \"Triggered by upstream build of $GITHUB_REPOSITORY: $(git log --oneline -n 1 HEAD)\"
          }}"

          echo "$(date): kick_travis.sh: kicking CI build for repo: nvenkatapavan/github-actions2, for branch [main]..."
          echo "POST on $URL"
          echo "$BODY"

          echo "Response:"
          curl -s -X POST \
          -H "Content-Type: application/json" \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.MY_TOKEN }}" \
          -d "$BODY" \
          "$URL" \
          | tee /tmp/actions-request-output.$$.txt

          if grep -q 'message' /tmp/actions-request-output.$$.txt; then
              echo "$(date): !!! kick_travis.sh: Got error kicking target repo."
              exit 1
          fi
  


